version: "3"

services:
  nginx-web:
    container_name: nginx-learn
    build: .
    ports:
      - "80:80"
    # volumes:
    #   - ./html:/usr/share/nginx/html
    # volumes:
    #   - html:/usr/share/nginx/html
# volumes:
#   html:
